### ISSUE TITLE
Photoshop CC 2019 

### ISSUE THREAD

**Issue by Avant1996** [Ikkyusan1/typeset-buddy#10]
I am having a problem using typeset buddy in Photoshop CC 2019. I downloaded it to the extensions folder but it wont show up in the Photoshop.

**Comment by Ikkyusan1** [comment]
I'm updating my systems in order to install CC2019. I'll test that in the weekend.
In the meantime, what OS are you on ?
Silly question : you say you've downloaded the extension, but have you unpacked the archive ?

**Comment by Avant1996** [comment]
I downloaded the extension and extracted it from the folder to the CEP
extension folder in photoshop. I'm use window 86x

**Comment by Ikkyusan1** [comment]
I've just tried it and it works.
I placed the unpacked archive in C:\Program Files (x86)\Common Files\Adobe\CEP\extensions

What precise OS are you using ? (to find the info, go to Control Panel\System and Security\System). The relevant info are listed under "Windows edition" and "System".

Edit: you can't be using a x86 install of PS CC2019 (and of Windows, for that matter) as they dropped the support of x86 environments with this version.

**Comment by Avant1996** [comment]
I'm using a 64-bit OS with windows 10.

**Comment by Gaxies** [comment]
Hi, I encountered the same problem. I'm using Photoshop CC 2019 and even though I unpacked the archive and placed the folder "typeset-buddy-master" in /Library/Application Support/Adobe/CEP/extensions, it won't show up in Photoshop.
My laptop is a MacBook pro, 15-inch model.
I've also tried to put only the "typeset_buddy_extension" folder (the one inside the "typeset-buddy-master" folder) in just to see what happened, and it did show up, but I received a notification that said it can't be launched because it is not properly signed.

**Comment by Ikkyusan1** [comment]
@Gaxies 
Well in your case, that's normal : you've downloaded the development files, not the release.
Try to download the release from here : https://github.com/Ikkyusan1/typeset-buddy/releases

@Avant1996 
I presume your problem is similar.

**Comment by Avant1996** [comment]
thanks you were right i downloaded the development files, not the release
