### ISSUE TITLE
Doesn't show up in PS

### ISSUE THREAD

**Issue by SlamBerrySlam** [Ikkyusan1/typeset-buddy#6]
I've recommended this to a number of people who are having trouble installing it. After adding the extracted files to C:\Program Files (86x)\Common Files\Adobe\CEP\extensions and to C:\Users{User}\App Data\Roaming\Adobe\CEP\extension, they open PS and can't find TS buddy under the Extensions menu. I'm not sure what to tell them. Do they add the json file in App Data as well? Is there an installer that will put everything in the proper place?

**Comment by Ikkyusan1** [comment]
There may be a problem indeed : to be honest, I haven't tested it on a Windows install for the latest releases. Can you give me some more details, like OS version, PS versions ?

**Comment by SlamBerrySlam** [comment]
I tried it on a Windows 7 64x machine and it didn't work for me either, but I'll ask everyone else what they're using and let you know. And I was using the trial version of PS 2018

**Comment by Ikkyusan1** [comment]
Yep, something's wrong, tested on Win7 PSCC2015.5, it doesn't work. I'll look into it.
Edit : although the extension doesn't work, it does appear in the menu WIndow>Extensions. The panel opens but doesn't display anything.

**Comment by SlamBerrySlam** [comment]
Thanks - a few ppl responded when I asked for OS and PS version. PS 2018 with Win 10 Home, PS 2017 with Win 10 (can't use the selection and then click on the text), Also CS6 on Win 7 & 10 
Edit: 1 more person responded and said CC 2015, Win 10 - getting error message, "The Typeset Buddy extension could not be loaded because it was not properly signed." The same person did add jsx file and posted it to present and a blank TS Buddy Robot window opened.

**Comment by Ikkyusan1** [comment]
Ok, now you're just being mean ! 
Joking ;-p

I think I've found the problem causing the extension not to load. Basically, the reason is the version of the Chromium framework that's embedded in PS. They differ from one version of PS to another, and apparently also between Windows or MacOS. It's a complete mess.
I'm testing a workaround on the PS versions that I have at hand.

For your compadre who can't use the extension on CS6, it is normal : typeset_buddy is an html extension and these aren't available on CS6. The feature is only available on PS CC.

For the other problems, I'll open separate issues.

**Comment by Ikkyusan1** [comment]
I've released a new version that should load on Windows. Tested on Win10 PS CC2015 and CC2017.
Please try it and tell us the result.

I'm now working on the other bugs you've mentioned and some others I've found during the tests (some cosmetic ones and some functional ones. There's something for everyone :-D ).

**Comment by SlamBerrySlam** [comment]
The people with CC2017 say the new version works. The others haven't gotten back to me yet.

**Comment by Ikkyusan1** [comment]
For all I know, the extension now loads properly on CC2017 on both Mac OSX and Win10.
